=== mdsamuelpastor/generacion/AL-Game/data/static_data/village/village_locations.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
	<xs:include schemaLocation="../import.xsd"/>
	<xs:element name="village_locations">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="village_location" type="villagelocation" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="villagelocation">
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="race" type="Race"/>
	</xs:complexType>
</xs:schema>

=== mdsamuelpastor/generacion/AL-Game/data/static_data/village/village_locations.xml
<?xml version="1.0" encoding="UTF-8"?>
<village_locations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="village_locations.xsd">
	<village_location id="1001" race="ELYOS"/>
	<village_location id="1002" race="ELYOS"/>
	<village_location id="1003" race="ELYOS"/>
	<village_location id="1004" race="ELYOS"/>
	<village_location id="1005" race="ELYOS"/>
	<village_location id="1006" race="ELYOS"/>
	<village_location id="1007" race="ELYOS"/>
	<village_location id="1008" race="ELYOS"/>
	<village_location id="1009" race="ELYOS"/>
	<village_location id="1010" race="ELYOS"/>
	<village_location id="1011" race="ELYOS"/>
	<village_location id="1012" race="ELYOS"/>
	<village_location id="1013" race="ELYOS"/>
	<village_location id="1014" race="ELYOS"/>
	<village_location id="1015" race="ELYOS"/>
	<village_location id="1016" race="ELYOS"/>
	<village_location id="1017" race="ELYOS"/>
	<village_location id="1018" race="ELYOS"/>
	<village_location id="1019" race="ELYOS"/>
	<village_location id="1020" race="ELYOS"/>
	<village_location id="1021" race="ELYOS"/>
	<village_location id="1022" race="ELYOS"/>
	<village_location id="1023" race="ELYOS"/>
	<village_location id="1024" race="ELYOS"/>
	<village_location id="1025" race="ELYOS"/>
	<village_location id="2001" race="ASMODIANS"/>
	<village_location id="2002" race="ASMODIANS"/>
	<village_location id="2003" race="ASMODIANS"/>
	<village_location id="2004" race="ASMODIANS"/>
	<village_location id="2005" race="ASMODIANS"/>
	<village_location id="2006" race="ASMODIANS"/>
	<village_location id="2007" race="ASMODIANS"/>
	<village_location id="2008" race="ASMODIANS"/>
	<village_location id="2009" race="ASMODIANS"/>
	<village_location id="2010" race="ASMODIANS"/>
	<village_location id="2011" race="ASMODIANS"/>
	<village_location id="2012" race="ASMODIANS"/>
	<village_location id="2013" race="ASMODIANS"/>
	<village_location id="2014" race="ASMODIANS"/>
	<village_location id="2015" race="ASMODIANS"/>
	<village_location id="2016" race="ASMODIANS"/>
	<village_location id="2017" race="ASMODIANS"/>
	<village_location id="2018" race="ASMODIANS"/>
	<village_location id="2019" race="ASMODIANS"/>
	<village_location id="2020" race="ASMODIANS"/>
	<village_location id="2021" race="ASMODIANS"/>
	<village_location id="2022" race="ASMODIANS"/>
	<village_location id="2023" race="ASMODIANS"/>
	<village_location id="2024" race="ASMODIANS"/>
	<village_location id="2025" race="ASMODIANS"/>
</village_locations>
