=== mdsamuelpastor/generacion/AL-Game/data/static_data/random_spawns/random_spawns.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="random_spawns" type="RandomSpawns"/>
	<xs:complexType name="RandomSpawns">
		<xs:sequence>
			<xs:element name="random_spawn" type="RandomSpawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RandomSpawn">
		<xs:sequence>
			<xs:element name="point" type="Point" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="npc_id" type="xs:int" use="required"/>
		<xs:attribute name="respawn_time" type="xs:int" use="required"/>
		<xs:attribute name="day_time" type="DayTime" use="optional" default="ALL"/>
	</xs:complexType>
	<xs:complexType name="Point">
		<xs:attribute name="map_id" type="xs:int" use="required"/>
		<xs:attribute name="instance_id" type="xs:int" use="optional" default="1"/>
		<xs:attribute name="x" type="xs:float" use="required"/>
		<xs:attribute name="y" type="xs:float" use="required"/>
		<xs:attribute name="z" type="xs:float" use="required"/>
		<xs:attribute name="h" type="HeadingType" use="optional" default="0"/>
	</xs:complexType>
	<xs:simpleType name="DayTime">
		<xs:restriction base="xs:string">
		<xs:enumeration value="ALL"/>
		<xs:enumeration value="DAY"/>
		<xs:enumeration value="NIGHT"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== mdsamuelpastor/generacion/AL-Game/data/static_data/random_spawns/random_spawns.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<random_spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="random_spawns.xsd">
    <!-- ELTNEN -->
    <!-- Fidget (Named Mob lvl:22) -->
    <random_spawn npc_id="210765" respawn_time="1800">
        <point map_id="210020000" x="765.80000" y="2227.33000" z="230.192001" h="112"/>
        <point map_id="210020000" x="756.63000" y="2823.63000" z="260.97687" h="17"/>
    </random_spawn>
    <!-- Galatia (Named Mob lvl:27) -->
    <random_spawn npc_id="210815" respawn_time="1800">
        <point map_id="210020000" x="1060.54000" y="2296.02000" z="243.072006" h="99"/>
        <point map_id="210020000" x="1018.78000" y="2130.08000" z="245.99815" h="49"/>
        <point map_id="210020000" x="1294.00000" y="2070.00000" z="264.12500" h="45"/>
        <point map_id="210020000" x="1215.71000" y="2206.33000" z="248.95000" h="28"/>
    </random_spawn>
    <!-- Akeras Stripeback (Named Mob Elite lvl:37) -->
    <random_spawn npc_id="210999" respawn_time="1800">
        <point map_id="210020000" x="1791.25000" y="740.25000" z="419.85938" h="32"/>
        <point map_id="210020000" x="1756.97000" y="665.94000" z="425.37500" h="79"/>
        <point map_id="210020000" x="1816.75000" y="796.25000" z="424.68750" h="116"/>
        <point map_id="210020000" x="1787.25000" y="749.75000" z="421.31250" h="37"/>
        <point map_id="210020000" x="1789.36000" y="765.14000" z="424.79877" h="51"/>
        <point map_id="210020000" x="1744.30000" y="772.92000" z="415.87500" h="100"/>
        <point map_id="210020000" x="1777.20000" y="682.42000" z="424.75000" h="95"/>
        <point map_id="210020000" x="1757.75000" y="792.75000" z="411.53125" h="10"/>
        <point map_id="210020000" x="1744.25000" y="777.75000" z="414.57812" h="71"/>
        <point map_id="210020000" x="1755.75000" y="792.25000" z="411.59375" h="10"/>
        <point map_id="210020000" x="1775.48000" y="770.95000" z="425.30374" h="1"/>
        <point map_id="210020000" x="1778.75000" y="684.52000" z="424.75000" h="82"/>
        <point map_id="210020000" x="1744.25000" y="773.75000" z="415.60938" h="8"/>
        <point map_id="210020000" x="1748.25000" y="756.25000" z="417.87500" h="62"/>
        <point map_id="210020000" x="1783.75000" y="699.75000" z="424.09375" h="2"/>
        <point map_id="210020000" x="1746.25000" y="782.25000" z="413.32812" h="109"/>
        <point map_id="210020000" x="1782.25000" y="725.75000" z="418.10938" h="28"/>
        <point map_id="210020000" x="1803.73000" y="765.75000" z="424.60938" h="94"/>
        <point map_id="210020000" x="1755.26000" y="665.00000" z="425.37500" h="26"/>
    </random_spawn>
    <!-- Queen Vespine (Named Mob lvl:23) -->
    <random_spawn npc_id="211645" respawn_time="1800">
        <point map_id="210020000" x="655.95000" y="2133.33000" z="220.75122" h="89"/>
        <point map_id="210020000" x="649.09000" y="2575.22000" z="230.12500" h="28"/>
        <point map_id="210020000" x="948.81000" y="2663.70000" z="265.68063" h="9"/>
        <point map_id="210020000" x="886.61000" y="2851.05000" z="264.18440" h="114"/>
    </random_spawn>
    <!-- Greatmage Teotem (Named Mob lvl:30) -->
    <random_spawn npc_id="211697" respawn_time="3600">
        <point map_id="210020000" x="1396.32000" y="2634.15000" z="298.75000" h="97"/>
        <point map_id="210020000" x="1397.40000" y="2606.69000" z="297.50000" h="19"/>
    </random_spawn>
    <!-- Spiritmaster Shapiel (Named Mob Elite lvl:40) -->
    <random_spawn npc_id="211704" respawn_time="3600">
        <point map_id="210020000" x="2736.40000" y="2714.30000" z="288.00000" h="57"/>
        <point map_id="210020000" x="2759.03000" y="2607.27000" z="293.06440" h="64"/>
        <point map_id="210020000" x="2749.23000" y="2605.34000" z="292.74310" h="111"/>
        <point map_id="210020000" x="2760.56000" y="2699.91000" z="287.25000" h="35"/>
    </random_spawn>
    <!-- Bladeclaw (Named Mob Elite lvl:40) -->
    <random_spawn npc_id="211711" respawn_time="3600">
        <point map_id="210020000" x="2210.75000" y="536.43000" z="434.44626" h="45"/>
        <point map_id="210020000" x="2210.19000" y="551.19000" z="433.87500" h="65"/>
        <point map_id="210020000" x="2578.75000" y="620.25000" z="464.01562" h="10"/>
        <point map_id="210020000" x="2566.73000" y="638.08000" z="460.95624" h="34"/>
        <point map_id="210020000" x="2223.75000" y="496.25000" z="438.37500" h="41"/>
        <point map_id="210020000" x="2553.54000" y="638.75000" z="457.24440" h="78"/>
        <point map_id="210020000" x="2564.45000" y="638.25000" z="460.47186" h="2"/>
        <point map_id="210020000" x="2590.25000" y="604.25000" z="468.93750" h="120"/>
        <point map_id="210020000" x="2591.12000" y="596.11000" z="471.91064" h="114"/>
        <point map_id="210020000" x="2544.03000" y="646.05000" z="454.25250" h="113"/>
        <point map_id="210020000" x="2240.69000" y="398.31000" z="466.94186" h="11"/>
        <point map_id="210020000" x="2226.47000" y="476.53000" z="439.31250" h="19"/>
        <point map_id="210020000" x="2221.82000" y="493.22000" z="438.57123" h="62"/>
    </random_spawn>
    <!-- Dekita (Named Mob Elite lvl:31) -->
    <random_spawn npc_id="211764" respawn_time="3600">
        <point map_id="210020000" x="442.34000" y="245.72000" z="209.01788" h="111"/>
        <point map_id="210020000" x="344.42000" y="241.54000" z="209.01822" h="40"/>
    </random_spawn>
    <!-- Summoned Sartemon (Named Mob Hero lvl:40) -->
    <random_spawn npc_id="211845" respawn_time="14400">
        <point map_id="210020000" x="2333.39000" y="354.84000" z="489.419006" h="5"/>
        <point map_id="210020000" x="2438.34000" y="316.35000" z="495.53937" h="51"/>
        <point map_id="210020000" x="2262.06000" y="483.42000" z="460.43124" h="91"/>
        <point map_id="210020000" x="2343.80000" y="355.12000" z="487.13750" h="61"/>
        <point map_id="210020000" x="2308.47000" y="365.43000" z="479.80750" h="51"/>
        <point map_id="210020000" x="2365.97000" y="370.36000" z="482.01126" h="103"/>
        <point map_id="210020000" x="2439.68000" y="319.80000" z="495.36250" h="112"/>
        <point map_id="210020000" x="2446.31000" y="359.88000" z="488.00000" h="97"/>
        <point map_id="210020000" x="2380.81000" y="320.58000" z="488.80250" h="44"/>
        <point map_id="210020000" x="2458.73000" y="356.30000" z="484.62940" h="102"/>
        <point map_id="210020000" x="2431.74000" y="312.17000" z="495.70688" h="100"/>
        <point map_id="210020000" x="2224.99000" y="457.58000" z="446.70502" h="93"/>
    </random_spawn>
    <!-- Crack Pathrunner (Named Mob Elite lvl:37) -->
    <random_spawn npc_id="211862" respawn_time="1600">
        <point map_id="210020000" x="2252.159912" y="1102.219971" z="389.705994" h="54"/>
        <point map_id="210020000" x="2052.73540" y="941.87980" z="416.29117" h="24"/>
        <point map_id="210020000" x="2162.54250" y="884.92240" z="420.75000" h="25"/>
        <point map_id="210020000" x="2150.89600" y="954.02930" z="413.37500" h="85"/>
    </random_spawn>
    <!-- Crack Pathrunner (Named Mob Elite lvl:38) -->
    <random_spawn npc_id="211863" respawn_time="1600">
        <point map_id="210020000" x="2400.429932" y="891.318970" z="450.165009" h="16"/>
        <point map_id="210020000" x="2331.37500" y="941.69507" z="444.85596" h="31"/>
        <point map_id="210020000" x="2231.91300" y="625.58540" z="449.12500" h="93"/>
        <point map_id="210020000" x="2298.37570" y="892.40020" z="451.47200" h="81"/>
        <point map_id="210020000" x="2159.66360" y="599.56610" z="453.47287" h="94"/>
        <point map_id="210020000" x="2184.28760" y="521.32544" z="446.83282" h="13"/>
        <point map_id="210020000" x="2254.58640" y="431.60855" z="476.25000" h="47"/>
        <point map_id="210020000" x="2181.91550" y="440.88168" z="452.37500" h="62"/>
    </random_spawn>
    <!-- Elder Pathrunner (Named Mob Elite lvl:39) -->
    <random_spawn npc_id="211864" respawn_time="1800">
        <point map_id="210020000" x="2406.780029" y="412.782013" z="487.12500" h="53"/>
        <point map_id="210020000" x="2458.40300" y="350.29465" z="485.79456" h="88"/>
        <point map_id="210020000" x="2295.06540" y="450.09140" z="488.00000" h="44"/>
        <point map_id="210020000" x="2480.89260" y="354.68173" z="492.74410" h="27"/>
        <point map_id="210020000" x="2464.92650" y="426.48322" z="494.37500" h="1"/>
    </random_spawn>
    <!-- Elder Pathrunner (Named Mob Elite lvl:40) -->
    <random_spawn npc_id="211865" respawn_time="1800">
        <point map_id="210020000" x="2464" y="591.036987" z="378.87500" h="22"/>
        <point map_id="210020000" x="2285.41110" y="733.43790" z="364.57193" h="77"/>
        <point map_id="210020000" x="2480.20830" y="658.98950" z="365.50262" h="9"/>
        <point map_id="210020000" x="2336.77600" y="552.98663" z="364.53530" h="97"/>
    </random_spawn>	
    <!-- INGGISON -->
    <!-- Chief Kurnus (Named Mob Elite lvl:53) -->
    <random_spawn npc_id="216501" respawn_time="7200">
        <point map_id="210050000" x="2710.36" y="509.686" h="48" z="347.23"/>
        <point map_id="210050000" x="2823.99" y="67.399" h="38" z="348.625"/>
        <point map_id="210050000" x="2913.88" y="596.966" h="63" z="345.75"/>
    </random_spawn>
    <!-- Glugbeard (Named Mob Elite lvl:52) -->
    <random_spawn npc_id="216503" respawn_time="7200">
        <point map_id="210050000" x="114.369" y="588.714" h="114" z="620.198"/>
        <point map_id="210050000" x="198.085" y="515.18" h="100" z="619.02"/>
    </random_spawn>
    <!-- Skuma Silvereye (Named Mob Elite lvl:54) -->
    <random_spawn npc_id="216507" respawn_time="7200">
        <point map_id="210050000" x="2184.71" y="1552.83" h="31" z="240.625"/>
